---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 12.1
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: ubuntu
    driver:
      box: ubuntu/xenial64
      #Please use ubuntu-14.04, nD apps will work only on 14.04
      customize:
        memory: 4000
        cpus: 2
      network:
        - ["private_network", {ip: "172.16.0.5"}]

suites:
  - name: default
    run_list:
      - recipe[jenkins::setup]
    attributes:
