---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 12.1
  always_update_cookbooks: true

platforms:
  - name: ubuntu
    driver:
      box: ubuntu/xenial64
      customize:
        memory: 2048
        cpus: 1

suites:
  - name: default
    run_list:
      - recipe[elk::setup]
    attributes:
